name: JSLint

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Add and Run Danger
        run: |
          yarn add danger --dev
          yarn danger init
      - name: Lint JS & HTML
        run: yarn danger --dangerfile "./checkers/js_dangerfile.js" ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint PLSQL
        run: yarn danger --dangerfile "./checkers/plsql_dangerfile.js" ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
