name: JSLint

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Add and Run Danger
        run: |
          yarn add danger --dev
          yarn danger init
          yarn danger --dangerfile "./js_dangerfile.js" ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
